# Generated by Django 3.0.4 on 2020-04-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='automobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='drpics')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
    ]
