# Generated by Django 3.0.4 on 2020-04-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0003_automobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='dentists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='denistsdoctors')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='denistsdoctors')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
    ]
