# Generated by Django 3.0.4 on 2020-04-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_dentists'),
    ]

    operations = [
        migrations.CreateModel(
            name='plumbercont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='plumber-c')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='plumber-c')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='plumberinstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='plumber-i')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='plumber-i')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='plumberproducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='plumber-p')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='plumber-p')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='plumberservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='plumber-s')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='plumber-s')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
    ]
