# Generated by Django 3.0.4 on 2020-05-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_electrician_hotel_reasurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancerhospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='cancerhospital')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='cancerhospital')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='childhospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='childhospital')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='childhospital')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ENThospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='ENThospital')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='ENThospital')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='eyehospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='eyehospital')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='eyehospital')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='hospital')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='hospital')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='mentalhospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='mentalhospital')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='mentalhospital')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='multisuperhospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='multisuperhospital')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='multisuperhospital')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='othrohospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='othrohospital')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='othrohospital')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='privatehospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='privatehospital')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='privatehospital')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='publichospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='publichospital')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='publichospital')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
    ]
