# Generated by Django 3.0.4 on 2020-05-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0007_cancerhospital_childhospital_enthospital_eyehospital_hospital_mentalhospital_multisuperhospital_othr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='othrohospital',
            new_name='orthrohospital',
        ),
    ]
