# Generated by Django 3.0.4 on 2020-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0008_auto_20200501_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='caracesseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='automobile')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='automobile')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='carrepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='automobile')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='automobile')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='cartyres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='automobile')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='automobile')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='carwash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='automobile')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='automobile')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='motercyclerepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='automobile')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='automobile')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='newcars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drimg', models.ImageField(upload_to='automobile')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('deprtimg', models.ImageField(upload_to='automobile')),
                ('department', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
            ],
        ),
    ]
