# Generated by Django 3.0.4 on 2020-05-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0013_auto_20200504_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestaddservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=50)),
                ('Speciality', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=20)),
                ('Address', models.TextField(max_length=200)),
                ('ServiceDescription', models.TextField(max_length=200)),
                ('img', models.ImageField(upload_to='req add')),
                ('Ownername', models.CharField(max_length=50)),
                ('Ownermobno', models.CharField(max_length=15)),
            ],
        ),
    ]
